### ISSUE TITLE
[Crash] Ticking entity

### ISSUE THREAD

**Issue by AceWolf456** [Mrbysco/JustARaftMod#8] opened 2019-02-06 08:30 UTC
We spawned in a raft and boom, crash. Yep, simple as that.
Crash Log:
https://pastebin.com/9Myu6SHk

**Comment by Mrbysco** [comment] 2019-02-06 19:57
What version are you using?

**Comment by AceWolf456** [comment] 2019-02-08 18:05
1.1.2

**Comment by Mrbysco** [comment] 2022-04-24 19:04
Duplicate of #5

**Closed as completed** 2022-04-24 19:04 UTC
